# Generated by Django 5.0.4 on 2024-04-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0002_delete_emocion'),
        ('pregunta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocionTexto', models.CharField(default='', max_length=100)),
                ('emocionImagen', models.CharField(default='', max_length=100)),
                ('emocion', models.CharField(default='', max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pregunta.pregunta')),
            ],
        ),
    ]
