# Generated by Django 5.0.4 on 2024-04-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emocion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emocion',
            name='respuesta',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='emocion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='emocionImagen',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='emocionTexto',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
