# Generated by Django 5.0.4 on 2024-04-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emocion', '0002_emocion_respuesta_alter_emocion_emocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocion',
            name='emocion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='emocionImagen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='emocionTexto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emocion',
            name='respuesta',
            field=models.CharField(max_length=255),
        ),
    ]
