# Generated by Django 5.0.4 on 2024-04-07 06:28

import docente.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='docente',
            managers=[
                ('objects', docente.models.CustomUserManager()),
            ],
        ),
    ]
