# Generated by Django 5.0.4 on 2024-04-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emocion',
        ),
    ]
